In [2]:
print(__doc__)

import numpy as np
import scipy as sp
import pandas as pd

from sklearn.preprocessing import Imputer

#read the csv into a dataframe
df = pd.read_csv('h1b_kaggle.csv')

Automatically created module for IPython interactive environment

In [3]:
df

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.00,2016.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.00,2016.0,"PLANO, TEXAS",-96.698886,33.019843
2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.00,2016.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.00,2016.0,"DENVER, COLORADO",-104.990251,39.739236
4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.40,2016.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003
5,6,CERTIFIED-WITHDRAWN,BURGER KING CORPORATION,CHIEF EXECUTIVES,"EXECUTIVE V P, GLOBAL DEVELOPMENT AND PRESIDEN...",Y,225000.00,2016.0,"MIAMI, FLORIDA",-80.191790,25.761680
6,7,CERTIFIED-WITHDRAWN,BT AND MK ENERGY AND COMMODITIES,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,91021.00,2016.0,"HOUSTON, TEXAS",-95.369803,29.760427
7,8,CERTIFIED-WITHDRAWN,"GLOBO MOBILE TECHNOLOGIES, INC.",CHIEF EXECUTIVES,CHIEF OPERATIONS OFFICER,Y,150000.00,2016.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
8,9,CERTIFIED-WITHDRAWN,ESI COMPANIES INC.,CHIEF EXECUTIVES,PRESIDENT,Y,127546.00,2016.0,"MEMPHIS, TEXAS",NaN,NaN
9,10,WITHDRAWN,LESSARD INTERNATIONAL LLC,CHIEF EXECUTIVES,PRESIDENT,Y,154648.00,2016.0,"VIENNA, VIRGINIA",-77.265260,38.901222
10,11,CERTIFIED-WITHDRAWN,H.J. HEINZ COMPANY,CHIEF EXECUTIVES,"CHIEF INFORMATION OFFICER, HEINZ NORTH AMERICA",Y,182978.00,2016.0,"PITTSBURGH, PENNSYLVANIA",-79.995886,40.440625
11,12,CERTIFIED-WITHDRAWN,DOW CORNING CORPORATION,CHIEF EXECUTIVES,VICE PRESIDENT AND CHIEF HUMAN RESOURCES OFFICER,Y,163717.00,2016.0,"MIDLAND, MICHIGAN",-84.247212,43.615583
12,13,CERTIFIED-WITHDRAWN,ACUSHNET COMPANY,CHIEF EXECUTIVES,TREASURER AND COO,Y,203860.80,2016.0,"FAIRHAVEN, MASSACHUSETTS",NaN,NaN
13,14,CERTIFIED-WITHDRAWN,"BIOCAIR, INC.",CHIEF EXECUTIVES,CHIEF COMMERCIAL OFFICER,Y,252637.00,2016.0,"MIAMI, FLORIDA",-80.191790,25.761680
14,15,CERTIFIED-WITHDRAWN,NEWMONT MINING CORPORATION,CHIEF EXECUTIVES,BOARD MEMBER,Y,105914.00,2016.0,"GREENWOOD VILLAGE, COLORADO",-104.950814,39.617210
15,16,CERTIFIED-WITHDRAWN,"VRICON, INC.",CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,153046.00,2016.0,"STERLING, VIRGINIA",-77.429130,39.006699
16,17,CERTIFIED-WITHDRAWN,CARDIAC SCIENCE CORPORATION,FINANCIAL MANAGERS,VICE PRESIDENT OF FINANCE,Y,90834.00,2016.0,"WAUKESHA, WISCONSIN",-88.231481,43.011678
17,18,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA",-118.243685,34.052234
18,19,CERTIFIED,QUICKLOGIX LLC,CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
19,20,CERTIFIED,"MCCHRYSTAL GROUP, LLC",CHIEF EXECUTIVES,"PRESIDENT, NORTHEAST REGION",Y,241842.00,2016.0,"ALEXANDRIA, VIRGINIA",-77.046921,38.804835
20,21,CERTIFIED-WITHDRAWN,"CUDDLE BARN, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER (COO),Y,117998.00,2016.0,"COMMERCE, CALIFORNIA",-118.159793,34.000569
21,22,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA",-118.243685,34.052234
22,23,CERTIFIED,"LOMICS, LLC",CHIEF EXECUTIVES,CEO,Y,99986.00,2016.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
23,24,CERTIFIED,UC UNIVERSITY HIGH SCHOOL EDUCATION INC.,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,99986.00,2016.0,"CHULA VISTA, CALIFORNIA",-117.084196,32.640054
24,25,CERTIFIED-WITHDRAWN,VMS COMMUNICATIONS LLC,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,159370.00,2016.0,"MIAMI, FLORIDA",-80.191790,25.761680
25,26,CERTIFIED,"QUICKLOGIX, INC.",CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
26,27,CERTIFIED-WITHDRAWN,FOODESSENTIALS CORPORATION,CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,130853.00,2016.0,"CHICAGO, ILLINOIS",-87.629798,41.878114
27,28,CERTIFIED,HELLO INC.,CHIEF EXECUTIVES,CHIEF BUSINESS OFFICER,Y,215862.00,2016.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
28,29,CERTIFIED,UMBEL CORP,CHIEF EXECUTIVES,VICE PRESIDENT OF ENGINEERING,Y,192088.00,2016.0,"AUSTIN, TEXAS",-97.743061,30.267153
29,30,CERTIFIED,"PERSPECTIVES OF FREEDOM FOUNDATION, INC",CHIEF EXECUTIVES,EXECUTIVE DIRECTOR,Y,95295.98,2016.0,"WESTON, FLORIDA",-80.399775,26.100365
...,...,...,...,...,...,...,...,...,...,...,...
3002428,3002429,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA",NaN,NaN
3002429,3002430,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA",NaN,NaN
3002430,3002431,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY",-74.412095,40.518715
3002431,3002432,WITHDRAWN,AT LAST SPORTSWEAR INC.,Computer Support Specialists,COMPUTER SUPPORT SPECIALIST,Y,36837.00,2011.0,"SECAUCUS, NEW JERSEY",-74.056530,40.789545
3002432,3002433,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY",-74.412095,40.518715
3002433,3002434,WITHDRAWN,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,Biochemists and Biophysicists,INSTRUCTOR,Y,36795.00,2011.0,"DALLAS, TEXAS",-96.796988,32.776664
3002434,3002435,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY",-74.412095,40.518715
3002435,3002436,WITHDRAWN,"MARLABS, INC",Computer Programmers,PROGRAMMER/ANALYST,Y,77730.00,2011.0,"DURHAM, NORTH CAROLINA",-78.898619,35.994033
3002436,3002437,WITHDRAWN,"XTRON SOFTWARE SERVICES, INC.",Computer Programmers,COMPUTER PROGRAMMERS,Y,89232.00,2011.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
3002437,3002438,WITHDRAWN,UNIVERSITY OF MISSISSIPPI MEDICAL CENTER,"Health Specialties Teachers, Postsecondary",ASSISTANT PROFESSOR OF ANESTHESIOLOGY,Y,34510.00,2011.0,"JACKSON, MISSISSIPPI",-90.184810,32.298757
3002438,3002439,WITHDRAWN,"CANVAS INFOTECH, INC.",Database Administrators,DATA ANALYST,Y,53082.00,2011.0,"PLEASANTON, CALIFORNIA",-121.874679,37.662431
3002439,3002440,WITHDRAWN,NEW YORK UNIVERSITY,"Biological Scientists, All Other",ADJUNCT ASSOCIATE PROFESSOR,Y,37336.00,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784
3002440,3002441,WITHDRAWN,"ORACLE AMERICA, INC.","Software Developers, Applications",SOFTWARE ENGINEER (SOFTWARE DEVELOPER 2),Y,64800.00,2011.0,"REDWOOD SHORES, CALIFORNIA",-122.245536,37.536413
3002441,3002442,WITHDRAWN,B & D DENTAL CORP.,Materials Scientists,MATERIALS SCIENTIST,N,70553.60,2011.0,"WEST VALLEY, UTAH",-112.001050,40.691613
3002442,3002443,WITHDRAWN,"MEDTECH STAFFING & SOLUTIONS, INC",Market Research Analysts and Marketing Special...,MARKET RESEARCH ANALYST,Y,33800.00,2011.0,"AKRON, OHIO",-81.519005,41.081445
3002443,3002444,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS",-71.367284,42.599814
3002444,3002445,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS",-71.367284,42.599814
3002445,3002446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"BERKLEY HEIGHTS, NEW JERSEY",-74.431052,40.680873
3002446,3002447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"SCHENECTADY , NEW YORK",-73.939569,42.814243
3002447,3002448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MOUTAIN VIEW, CALIFORNIA",-122.083851,37.386052
3002448,3002449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ST.PAUL, MINNESOTA",-93.089958,44.953703
3002449,3002450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"NEW TOWN, PENNSYLVANIA",-74.932260,40.228337
3002450,3002451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"WESTMINISTER, COLORADO",-105.037205,39.836653
3002451,3002452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FREEMONT, CALIFORNIA",-121.988572,37.548270
3002452,3002453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LAVERGNE, TENNESSEE",-86.581939,36.015618
3002453,3002454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"NYC, NEW YORK",-74.005941,40.712784
3002454,3002455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"SOUTH LAKE, TEXAS",-97.134178,32.941236
3002455,3002456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CLINTON, NEW JERSEY",-74.909890,40.636768
3002456,3002457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OWINGS MILL, MARYLAND",-76.780253,39.419550
3002457,3002458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ALTANTA, GEORGIA",-84.387982,33.748995

In [5]:
df.count()

Unnamed: 0            3002458
CASE_STATUS           3002445
EMPLOYER_NAME         3002399
SOC_NAME              2984724
JOB_TITLE             3002415
FULL_TIME_POSITION    3002443
PREVAILING_WAGE       3002373
YEAR                  3002445
WORKSITE              3002458
lon                   2895216
lat                   2895216
dtype: int64

In [6]:
df.describe()

         Unnamed: 0  PREVAILING_WAGE          YEAR           lon           lat
count  3.002458e+06     3.002373e+06  3.002445e+06  2.895216e+06  2.895216e+06
mean   1.501230e+06     1.469984e+05  2.013855e+03 -9.213441e+01  3.816054e+01
std    8.667351e+05     5.287609e+06  1.680612e+00  1.965591e+01  4.672835e+00
min    1.000000e+00     0.000000e+00  2.011000e+03 -1.578583e+02  1.343719e+01
25%    7.506152e+05     5.437100e+04  2.012000e+03 -1.119261e+02  3.416536e+01
50%    1.501230e+06     6.502100e+04  2.014000e+03 -8.615862e+01  3.910312e+01
75%    2.251844e+06     8.143200e+04  2.015000e+03 -7.551381e+01  4.088374e+01
max    3.002458e+06     6.997607e+09  2.016000e+03  1.457298e+02  6.483778e+01

In [7]:
df1 = df.dropna()
df1.count()

Unnamed: 0            2877765
CASE_STATUS           2877765
EMPLOYER_NAME         2877765
SOC_NAME              2877765
JOB_TITLE             2877765
FULL_TIME_POSITION    2877765
PREVAILING_WAGE       2877765
YEAR                  2877765
WORKSITE              2877765
lon                   2877765
lat                   2877765
dtype: int64

In [9]:
df2 = df.drop(df.columns[[9, 10]], axis=1)

In [10]:
df2.count()

Unnamed: 0            3002458
CASE_STATUS           3002445
EMPLOYER_NAME         3002399
SOC_NAME              2984724
JOB_TITLE             3002415
FULL_TIME_POSITION    3002443
PREVAILING_WAGE       3002373
YEAR                  3002445
WORKSITE              3002458
dtype: int64

In [13]:
len(df.SOC_NAME.unique())

2133

In [14]:
len(df.JOB_TITLE.unique())

287550

In [15]:
len(df.EMPLOYER_NAME.unique())

236014

In [18]:
len(df.CASE_STATUS.unique())
df.CASE_STATUS.unique()

array(['CERTIFIED-WITHDRAWN', 'WITHDRAWN', 'CERTIFIED', 'DENIED',
       'REJECTED', 'INVALIDATED',
       'PENDING QUALITY AND COMPLIANCE REVIEW - UNASSIGNED', nan], dtype=object)

In [19]:
len(df.WORKSITE.unique())

18622

In [21]:
df3 = df2.dropna(subset=['FULL_TIME_POSITION'])
df3.count()

Unnamed: 0            3002443
CASE_STATUS           3002443
EMPLOYER_NAME         3002398
SOC_NAME              2984722
JOB_TITLE             3002414
FULL_TIME_POSITION    3002443
PREVAILING_WAGE       3002373
YEAR                  3002443
WORKSITE              3002443
dtype: int64

In [25]:
final_df = df.drop(df.columns[[9, 10]], axis=1).dropna()
final_df.count()

Unnamed: 0            2984609
CASE_STATUS           2984609
EMPLOYER_NAME         2984609
SOC_NAME              2984609
JOB_TITLE             2984609
FULL_TIME_POSITION    2984609
PREVAILING_WAGE       2984609
YEAR                  2984609
WORKSITE              2984609
dtype: int64

In [26]:
final_df.describe()

         Unnamed: 0  PREVAILING_WAGE          YEAR
count  2.984609e+06     2.984609e+06  2.984609e+06
mean   1.496684e+06     1.469658e+05  2.013864e+03
std    8.663691e+05     5.296147e+06  1.678808e+00
min    1.000000e+00     0.000000e+00  2.011000e+03
25%    7.461800e+05     5.435000e+04  2.012000e+03
50%    1.494035e+06     6.500000e+04  2.014000e+03
75%    2.246552e+06     8.143200e+04  2.015000e+03
max    3.002445e+06     6.997607e+09  2.016000e+03

In [27]:
final_df

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE
0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.00,2016.0,"ANN ARBOR, MICHIGAN"
1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.00,2016.0,"PLANO, TEXAS"
2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.00,2016.0,"JERSEY CITY, NEW JERSEY"
3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.00,2016.0,"DENVER, COLORADO"
4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.40,2016.0,"ST. LOUIS, MISSOURI"
5,6,CERTIFIED-WITHDRAWN,BURGER KING CORPORATION,CHIEF EXECUTIVES,"EXECUTIVE V P, GLOBAL DEVELOPMENT AND PRESIDEN...",Y,225000.00,2016.0,"MIAMI, FLORIDA"
6,7,CERTIFIED-WITHDRAWN,BT AND MK ENERGY AND COMMODITIES,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,91021.00,2016.0,"HOUSTON, TEXAS"
7,8,CERTIFIED-WITHDRAWN,"GLOBO MOBILE TECHNOLOGIES, INC.",CHIEF EXECUTIVES,CHIEF OPERATIONS OFFICER,Y,150000.00,2016.0,"SAN JOSE, CALIFORNIA"
8,9,CERTIFIED-WITHDRAWN,ESI COMPANIES INC.,CHIEF EXECUTIVES,PRESIDENT,Y,127546.00,2016.0,"MEMPHIS, TEXAS"
9,10,WITHDRAWN,LESSARD INTERNATIONAL LLC,CHIEF EXECUTIVES,PRESIDENT,Y,154648.00,2016.0,"VIENNA, VIRGINIA"
10,11,CERTIFIED-WITHDRAWN,H.J. HEINZ COMPANY,CHIEF EXECUTIVES,"CHIEF INFORMATION OFFICER, HEINZ NORTH AMERICA",Y,182978.00,2016.0,"PITTSBURGH, PENNSYLVANIA"
11,12,CERTIFIED-WITHDRAWN,DOW CORNING CORPORATION,CHIEF EXECUTIVES,VICE PRESIDENT AND CHIEF HUMAN RESOURCES OFFICER,Y,163717.00,2016.0,"MIDLAND, MICHIGAN"
12,13,CERTIFIED-WITHDRAWN,ACUSHNET COMPANY,CHIEF EXECUTIVES,TREASURER AND COO,Y,203860.80,2016.0,"FAIRHAVEN, MASSACHUSETTS"
13,14,CERTIFIED-WITHDRAWN,"BIOCAIR, INC.",CHIEF EXECUTIVES,CHIEF COMMERCIAL OFFICER,Y,252637.00,2016.0,"MIAMI, FLORIDA"
14,15,CERTIFIED-WITHDRAWN,NEWMONT MINING CORPORATION,CHIEF EXECUTIVES,BOARD MEMBER,Y,105914.00,2016.0,"GREENWOOD VILLAGE, COLORADO"
15,16,CERTIFIED-WITHDRAWN,"VRICON, INC.",CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,153046.00,2016.0,"STERLING, VIRGINIA"
16,17,CERTIFIED-WITHDRAWN,CARDIAC SCIENCE CORPORATION,FINANCIAL MANAGERS,VICE PRESIDENT OF FINANCE,Y,90834.00,2016.0,"WAUKESHA, WISCONSIN"
17,18,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA"
18,19,CERTIFIED,QUICKLOGIX LLC,CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA"
19,20,CERTIFIED,"MCCHRYSTAL GROUP, LLC",CHIEF EXECUTIVES,"PRESIDENT, NORTHEAST REGION",Y,241842.00,2016.0,"ALEXANDRIA, VIRGINIA"
20,21,CERTIFIED-WITHDRAWN,"CUDDLE BARN, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER (COO),Y,117998.00,2016.0,"COMMERCE, CALIFORNIA"
21,22,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA"
22,23,CERTIFIED,"LOMICS, LLC",CHIEF EXECUTIVES,CEO,Y,99986.00,2016.0,"SAN DIEGO, CALIFORNIA"
23,24,CERTIFIED,UC UNIVERSITY HIGH SCHOOL EDUCATION INC.,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,99986.00,2016.0,"CHULA VISTA, CALIFORNIA"
24,25,CERTIFIED-WITHDRAWN,VMS COMMUNICATIONS LLC,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,159370.00,2016.0,"MIAMI, FLORIDA"
25,26,CERTIFIED,"QUICKLOGIX, INC.",CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA"
26,27,CERTIFIED-WITHDRAWN,FOODESSENTIALS CORPORATION,CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,130853.00,2016.0,"CHICAGO, ILLINOIS"
27,28,CERTIFIED,HELLO INC.,CHIEF EXECUTIVES,CHIEF BUSINESS OFFICER,Y,215862.00,2016.0,"SAN FRANCISCO, CALIFORNIA"
28,29,CERTIFIED,UMBEL CORP,CHIEF EXECUTIVES,VICE PRESIDENT OF ENGINEERING,Y,192088.00,2016.0,"AUSTIN, TEXAS"
29,30,CERTIFIED,"PERSPECTIVES OF FREEDOM FOUNDATION, INC",CHIEF EXECUTIVES,EXECUTIVE DIRECTOR,Y,95295.98,2016.0,"WESTON, FLORIDA"
...,...,...,...,...,...,...,...,...,...
3002415,3002416,WITHDRAWN,"MEDTRONIC, INC.",Computer Systems Analysts,SR. IT BUSINESS SYSTEMS ANALYST,Y,76981.00,2011.0,"MOUNDS VIEW, MINNESOTA"
3002416,3002417,WITHDRAWN,"COMPUNNEL SOFTWARE GROUP, INC.",Computer Systems Analysts,SYSTEMS ANALYST,Y,41538.00,2011.0,"NASHVILLE, TENNESSEE"
3002417,3002418,WITHDRAWN,BENZ 'N BEAMERS,Accountants and Auditors,ACCOUNTANT,Y,38604.80,2011.0,"LOMITA, CALIFORNIA"
3002418,3002419,WITHDRAWN,"HIVE-FX, LLC",Multimedia Artists and Animators,3D ARTIST,Y,50544.00,2011.0,"PORTLAND, OREGON"
3002419,3002420,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002420,3002421,WITHDRAWN,"GS GLOBAL SERVICES, INC.",Computer Programmers,IT CONSULTANT,Y,70554.00,2011.0,"MANALAPAN, NEW JERSEY"
3002421,3002422,WITHDRAWN,"UNITED SOFTWARE GROUP, INC.",Network and Computer Systems Administrators*,WEBSPHERE PORTAL SYSTEM ADMINISTRATOR,Y,45843.00,2011.0,"DUBLIN, OHIO"
3002422,3002423,WITHDRAWN,LSI CORPORATION,"Electronics Engineers, Except Computer",ASIC DESIGN ENGINEER,Y,57158.00,2011.0,"ALLENTOWN, PENNSYLVANIA"
3002423,3002424,WITHDRAWN,"KASEYA DEVELOPMENT, LLC","Software Developers, Applications",SR. SOFTWARE ENGINEER,Y,93100.00,2011.0,"SAN JOSE, CALIFORNIA"
3002424,3002425,WITHDRAWN,"KASEYA DEVELOPMENT, LLC","Software Developers, Applications",SR. SOFTWARE ENGINEER,Y,93100.00,2011.0,"SAN JOSE, CALIFORNIA"
3002425,3002426,WITHDRAWN,MIFI SYSTEMS INC,Computer Systems Analysts,SYSTEMS ANALYST,Y,50939.00,2011.0,"CLEARWATER, FLORIDA"
3002426,3002427,WITHDRAWN,COVANCE CLINICAL RESEARCH UNIT INC.,Statisticians,BIOSTATISTICIAN I,Y,55640.00,2011.0,"MADISON, WISCONSIN"
3002427,3002428,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Programmers,COMPUTER PROGRAMMER,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002428,3002429,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA"
3002429,3002430,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA"
3002430,3002431,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002431,3002432,WITHDRAWN,AT LAST SPORTSWEAR INC.,Computer Support Specialists,COMPUTER SUPPORT SPECIALIST,Y,36837.00,2011.0,"SECAUCUS, NEW JERSEY"
3002432,3002433,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002433,3002434,WITHDRAWN,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,Biochemists and Biophysicists,INSTRUCTOR,Y,36795.00,2011.0,"DALLAS, TEXAS"
3002434,3002435,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002435,3002436,WITHDRAWN,"MARLABS, INC",Computer Programmers,PROGRAMMER/ANALYST,Y,77730.00,2011.0,"DURHAM, NORTH CAROLINA"
3002436,3002437,WITHDRAWN,"XTRON SOFTWARE SERVICES, INC.",Computer Programmers,COMPUTER PROGRAMMERS,Y,89232.00,2011.0,"SANTA CLARA, CALIFORNIA"
3002437,3002438,WITHDRAWN,UNIVERSITY OF MISSISSIPPI MEDICAL CENTER,"Health Specialties Teachers, Postsecondary",ASSISTANT PROFESSOR OF ANESTHESIOLOGY,Y,34510.00,2011.0,"JACKSON, MISSISSIPPI"
3002438,3002439,WITHDRAWN,"CANVAS INFOTECH, INC.",Database Administrators,DATA ANALYST,Y,53082.00,2011.0,"PLEASANTON, CALIFORNIA"
3002439,3002440,WITHDRAWN,NEW YORK UNIVERSITY,"Biological Scientists, All Other",ADJUNCT ASSOCIATE PROFESSOR,Y,37336.00,2011.0,"NEW YORK, NEW YORK"
3002440,3002441,WITHDRAWN,"ORACLE AMERICA, INC.","Software Developers, Applications",SOFTWARE ENGINEER (SOFTWARE DEVELOPER 2),Y,64800.00,2011.0,"REDWOOD SHORES, CALIFORNIA"
3002441,3002442,WITHDRAWN,B & D DENTAL CORP.,Materials Scientists,MATERIALS SCIENTIST,N,70553.60,2011.0,"WEST VALLEY, UTAH"
3002442,3002443,WITHDRAWN,"MEDTECH STAFFING & SOLUTIONS, INC",Market Research Analysts and Marketing Special...,MARKET RESEARCH ANALYST,Y,33800.00,2011.0,"AKRON, OHIO"
3002443,3002444,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS"
3002444,3002445,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS"

In [28]:
final_df.rename(columns={'Unnamed: 0':'ID'}, inplace=True)
final_df.count()

ID                    2984609
CASE_STATUS           2984609
EMPLOYER_NAME         2984609
SOC_NAME              2984609
JOB_TITLE             2984609
FULL_TIME_POSITION    2984609
PREVAILING_WAGE       2984609
YEAR                  2984609
WORKSITE              2984609
dtype: int64

In [29]:
final_df['CASE_STATUS'].value_counts()

CERTIFIED                                             2600241
CERTIFIED-WITHDRAWN                                    201479
DENIED                                                  93761
WITHDRAWN                                               89110
PENDING QUALITY AND COMPLIANCE REVIEW - UNASSIGNED         15
REJECTED                                                    2
INVALIDATED                                                 1
Name: CASE_STATUS, dtype: int64

In [30]:
final_df1 = final_df[final_df.CASE_STATUS != "INVALIDATED"]
final_df1['CASE_STATUS'].value_counts()

CERTIFIED                                             2600241
CERTIFIED-WITHDRAWN                                    201479
DENIED                                                  93761
WITHDRAWN                                               89110
PENDING QUALITY AND COMPLIANCE REVIEW - UNASSIGNED         15
REJECTED                                                    2
Name: CASE_STATUS, dtype: int64

In [31]:
to_drop = ["INVALIDATED","REJECTED","PENDING QUALITY AND COMPLIANCE REVIEW - UNASSIGNED"]
final_df2 = final_df[~final_df['CASE_STATUS'].isin(to_drop)]
final_df2['CASE_STATUS'].value_counts()

CERTIFIED              2600241
CERTIFIED-WITHDRAWN     201479
DENIED                   93761
WITHDRAWN                89110
Name: CASE_STATUS, dtype: int64

In [33]:
final_df2

,ID,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE
0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.00,2016.0,"ANN ARBOR, MICHIGAN"
1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.00,2016.0,"PLANO, TEXAS"
2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.00,2016.0,"JERSEY CITY, NEW JERSEY"
3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.00,2016.0,"DENVER, COLORADO"
4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.40,2016.0,"ST. LOUIS, MISSOURI"
5,6,CERTIFIED-WITHDRAWN,BURGER KING CORPORATION,CHIEF EXECUTIVES,"EXECUTIVE V P, GLOBAL DEVELOPMENT AND PRESIDEN...",Y,225000.00,2016.0,"MIAMI, FLORIDA"
6,7,CERTIFIED-WITHDRAWN,BT AND MK ENERGY AND COMMODITIES,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,91021.00,2016.0,"HOUSTON, TEXAS"
7,8,CERTIFIED-WITHDRAWN,"GLOBO MOBILE TECHNOLOGIES, INC.",CHIEF EXECUTIVES,CHIEF OPERATIONS OFFICER,Y,150000.00,2016.0,"SAN JOSE, CALIFORNIA"
8,9,CERTIFIED-WITHDRAWN,ESI COMPANIES INC.,CHIEF EXECUTIVES,PRESIDENT,Y,127546.00,2016.0,"MEMPHIS, TEXAS"
9,10,WITHDRAWN,LESSARD INTERNATIONAL LLC,CHIEF EXECUTIVES,PRESIDENT,Y,154648.00,2016.0,"VIENNA, VIRGINIA"
10,11,CERTIFIED-WITHDRAWN,H.J. HEINZ COMPANY,CHIEF EXECUTIVES,"CHIEF INFORMATION OFFICER, HEINZ NORTH AMERICA",Y,182978.00,2016.0,"PITTSBURGH, PENNSYLVANIA"
11,12,CERTIFIED-WITHDRAWN,DOW CORNING CORPORATION,CHIEF EXECUTIVES,VICE PRESIDENT AND CHIEF HUMAN RESOURCES OFFICER,Y,163717.00,2016.0,"MIDLAND, MICHIGAN"
12,13,CERTIFIED-WITHDRAWN,ACUSHNET COMPANY,CHIEF EXECUTIVES,TREASURER AND COO,Y,203860.80,2016.0,"FAIRHAVEN, MASSACHUSETTS"
13,14,CERTIFIED-WITHDRAWN,"BIOCAIR, INC.",CHIEF EXECUTIVES,CHIEF COMMERCIAL OFFICER,Y,252637.00,2016.0,"MIAMI, FLORIDA"
14,15,CERTIFIED-WITHDRAWN,NEWMONT MINING CORPORATION,CHIEF EXECUTIVES,BOARD MEMBER,Y,105914.00,2016.0,"GREENWOOD VILLAGE, COLORADO"
15,16,CERTIFIED-WITHDRAWN,"VRICON, INC.",CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,153046.00,2016.0,"STERLING, VIRGINIA"
16,17,CERTIFIED-WITHDRAWN,CARDIAC SCIENCE CORPORATION,FINANCIAL MANAGERS,VICE PRESIDENT OF FINANCE,Y,90834.00,2016.0,"WAUKESHA, WISCONSIN"
17,18,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA"
18,19,CERTIFIED,QUICKLOGIX LLC,CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA"
19,20,CERTIFIED,"MCCHRYSTAL GROUP, LLC",CHIEF EXECUTIVES,"PRESIDENT, NORTHEAST REGION",Y,241842.00,2016.0,"ALEXANDRIA, VIRGINIA"
20,21,CERTIFIED-WITHDRAWN,"CUDDLE BARN, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER (COO),Y,117998.00,2016.0,"COMMERCE, CALIFORNIA"
21,22,CERTIFIED-WITHDRAWN,WESTFIELD CORPORATION,CHIEF EXECUTIVES,"GENERAL MANAGER, OPERATIONS",Y,164050.00,2016.0,"LOS ANGELES, CALIFORNIA"
22,23,CERTIFIED,"LOMICS, LLC",CHIEF EXECUTIVES,CEO,Y,99986.00,2016.0,"SAN DIEGO, CALIFORNIA"
23,24,CERTIFIED,UC UNIVERSITY HIGH SCHOOL EDUCATION INC.,CHIEF EXECUTIVES,CHIEF FINANCIAL OFFICER,Y,99986.00,2016.0,"CHULA VISTA, CALIFORNIA"
24,25,CERTIFIED-WITHDRAWN,VMS COMMUNICATIONS LLC,CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,159370.00,2016.0,"MIAMI, FLORIDA"
25,26,CERTIFIED,"QUICKLOGIX, INC.",CHIEF EXECUTIVES,CEO,Y,187200.00,2016.0,"SANTA CLARA, CALIFORNIA"
26,27,CERTIFIED-WITHDRAWN,FOODESSENTIALS CORPORATION,CHIEF EXECUTIVES,CHIEF EXECUTIVE OFFICER,Y,130853.00,2016.0,"CHICAGO, ILLINOIS"
27,28,CERTIFIED,HELLO INC.,CHIEF EXECUTIVES,CHIEF BUSINESS OFFICER,Y,215862.00,2016.0,"SAN FRANCISCO, CALIFORNIA"
28,29,CERTIFIED,UMBEL CORP,CHIEF EXECUTIVES,VICE PRESIDENT OF ENGINEERING,Y,192088.00,2016.0,"AUSTIN, TEXAS"
29,30,CERTIFIED,"PERSPECTIVES OF FREEDOM FOUNDATION, INC",CHIEF EXECUTIVES,EXECUTIVE DIRECTOR,Y,95295.98,2016.0,"WESTON, FLORIDA"
...,...,...,...,...,...,...,...,...,...
3002415,3002416,WITHDRAWN,"MEDTRONIC, INC.",Computer Systems Analysts,SR. IT BUSINESS SYSTEMS ANALYST,Y,76981.00,2011.0,"MOUNDS VIEW, MINNESOTA"
3002416,3002417,WITHDRAWN,"COMPUNNEL SOFTWARE GROUP, INC.",Computer Systems Analysts,SYSTEMS ANALYST,Y,41538.00,2011.0,"NASHVILLE, TENNESSEE"
3002417,3002418,WITHDRAWN,BENZ 'N BEAMERS,Accountants and Auditors,ACCOUNTANT,Y,38604.80,2011.0,"LOMITA, CALIFORNIA"
3002418,3002419,WITHDRAWN,"HIVE-FX, LLC",Multimedia Artists and Animators,3D ARTIST,Y,50544.00,2011.0,"PORTLAND, OREGON"
3002419,3002420,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002420,3002421,WITHDRAWN,"GS GLOBAL SERVICES, INC.",Computer Programmers,IT CONSULTANT,Y,70554.00,2011.0,"MANALAPAN, NEW JERSEY"
3002421,3002422,WITHDRAWN,"UNITED SOFTWARE GROUP, INC.",Network and Computer Systems Administrators*,WEBSPHERE PORTAL SYSTEM ADMINISTRATOR,Y,45843.00,2011.0,"DUBLIN, OHIO"
3002422,3002423,WITHDRAWN,LSI CORPORATION,"Electronics Engineers, Except Computer",ASIC DESIGN ENGINEER,Y,57158.00,2011.0,"ALLENTOWN, PENNSYLVANIA"
3002423,3002424,WITHDRAWN,"KASEYA DEVELOPMENT, LLC","Software Developers, Applications",SR. SOFTWARE ENGINEER,Y,93100.00,2011.0,"SAN JOSE, CALIFORNIA"
3002424,3002425,WITHDRAWN,"KASEYA DEVELOPMENT, LLC","Software Developers, Applications",SR. SOFTWARE ENGINEER,Y,93100.00,2011.0,"SAN JOSE, CALIFORNIA"
3002425,3002426,WITHDRAWN,MIFI SYSTEMS INC,Computer Systems Analysts,SYSTEMS ANALYST,Y,50939.00,2011.0,"CLEARWATER, FLORIDA"
3002426,3002427,WITHDRAWN,COVANCE CLINICAL RESEARCH UNIT INC.,Statisticians,BIOSTATISTICIAN I,Y,55640.00,2011.0,"MADISON, WISCONSIN"
3002427,3002428,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Programmers,COMPUTER PROGRAMMER,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002428,3002429,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA"
3002429,3002430,WITHDRAWN,AVANT HEALTHCARE PROFESSIONALS,Physical Therapists,PHYSICAL THERAPIST,Y,53601.60,2011.0,"LEBANON, PENNSYLVANIA"
3002430,3002431,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002431,3002432,WITHDRAWN,AT LAST SPORTSWEAR INC.,Computer Support Specialists,COMPUTER SUPPORT SPECIALIST,Y,36837.00,2011.0,"SECAUCUS, NEW JERSEY"
3002432,3002433,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002433,3002434,WITHDRAWN,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,Biochemists and Biophysicists,INSTRUCTOR,Y,36795.00,2011.0,"DALLAS, TEXAS"
3002434,3002435,WITHDRAWN,"TRISYNC TECHNOLOGIES, INC.",Computer Systems Analysts,COMPUTER SYSTEM ANALYST,Y,55245.00,2011.0,"EDISON, NEW JERSEY"
3002435,3002436,WITHDRAWN,"MARLABS, INC",Computer Programmers,PROGRAMMER/ANALYST,Y,77730.00,2011.0,"DURHAM, NORTH CAROLINA"
3002436,3002437,WITHDRAWN,"XTRON SOFTWARE SERVICES, INC.",Computer Programmers,COMPUTER PROGRAMMERS,Y,89232.00,2011.0,"SANTA CLARA, CALIFORNIA"
3002437,3002438,WITHDRAWN,UNIVERSITY OF MISSISSIPPI MEDICAL CENTER,"Health Specialties Teachers, Postsecondary",ASSISTANT PROFESSOR OF ANESTHESIOLOGY,Y,34510.00,2011.0,"JACKSON, MISSISSIPPI"
3002438,3002439,WITHDRAWN,"CANVAS INFOTECH, INC.",Database Administrators,DATA ANALYST,Y,53082.00,2011.0,"PLEASANTON, CALIFORNIA"
3002439,3002440,WITHDRAWN,NEW YORK UNIVERSITY,"Biological Scientists, All Other",ADJUNCT ASSOCIATE PROFESSOR,Y,37336.00,2011.0,"NEW YORK, NEW YORK"
3002440,3002441,WITHDRAWN,"ORACLE AMERICA, INC.","Software Developers, Applications",SOFTWARE ENGINEER (SOFTWARE DEVELOPER 2),Y,64800.00,2011.0,"REDWOOD SHORES, CALIFORNIA"
3002441,3002442,WITHDRAWN,B & D DENTAL CORP.,Materials Scientists,MATERIALS SCIENTIST,N,70553.60,2011.0,"WEST VALLEY, UTAH"
3002442,3002443,WITHDRAWN,"MEDTECH STAFFING & SOLUTIONS, INC",Market Research Analysts and Marketing Special...,MARKET RESEARCH ANALYST,Y,33800.00,2011.0,"AKRON, OHIO"
3002443,3002444,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS"
3002444,3002445,WITHDRAWN,LARSEN & TOUBRO LIMITED,Commercial and Industrial Designers,DESIGN ENGINEER,Y,59800.00,2011.0,"CHELMSFORD, MASSACHUSETTS"

In [34]:
final_df2.YEAR.unique()
len(final_df2.YEAR.unique())

6

In [35]:
final_df2.YEAR.unique()

array([ 2016.,  2015.,  2014.,  2013.,  2012.,  2011.])